name: opencode

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  workflow_call:

jobs:
  opencode:
    if: |
      contains(github.event.comment.body, '/oc') ||
      contains(github.event.comment.body, '/opencode')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: read
      issues: read
    steps:
       - name: Checkout repository
         uses: actions/checkout@v6
         with:
           fetch-depth: 1
           persist-credentials: false
       - name: Run OpenCode
         uses: anomalyco/opencode/github@latest
         with:
           model: opencode/minimax-m2.5-free